controllers:
    resource: ../../src/Controller/
    type: annotation
api_bids_auth:
    resource: ../../src/Auth/Controller/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
